'use client'
import {useCallback,useEffect,useState} from 'react'
import Button from '../../components/ui/Button'
import Modal from '../../components/ui/Modal'
import {getActiveWorkspace} from '../../lib/business-context'
import {requireSupabase} from '../../lib/supabase'

type Props={mode:'categories'|'units'}
export default function MasterDataWorkspace({mode}:Props){const db=requireSupabase();const isCat=mode==='categories';const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[symbol,setSymbol]=useState(''),[dec,setDec]=useState('0'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError('');try{const w=await getActiveWorkspace();let q=db.from(isCat?'categories':'units').select('*').eq('business_id',w.business.id).order('name');const r=await q;if(r.error)throw r.error;setRows(r.data||[])}catch(e:any){setError(e?.message||'Gagal memuat data.')}finally{setLoading(false)}},[db,isCat]);useEffect(()=>{load()},[load])
 function start(r?:any){setEdit(r||null);setName(r?.name||'');setCode(r?.code||'');setSymbol(r?.symbol||'');setDec(String(r?.decimal_places??0));setError('');setOpen(true)}
 function makeCode(v:string){return v.trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,30)}
 async function save(){if(!name.trim()){setError(`Nama ${isCat?'kategori':'satuan'} wajib diisi.`);return}const c=(code.trim()||makeCode(name));if(!c){setError('Kode tidak valid.');return}setSaving(true);setError('');try{const w=await getActiveWorkspace();const payload:any={name:name.trim(),code:c};if(!isCat){payload.symbol=symbol.trim()||null;payload.decimal_places=Math.max(0,Math.min(6,Number(dec||0)))}if(edit){const r=await db.from(isCat?'categories':'units').update(payload).eq('id',edit.id).eq('business_id',w.business.id);if(r.error)throw r.error}else{const r=await db.from(isCat?'categories':'units').insert({...payload,business_id:w.business.id,is_active:true});if(r.error)throw r.error}setOpen(false);await load()}catch(e:any){setError(e?.message||'Gagal menyimpan data. Pastikan kode belum digunakan.')}finally{setSaving(false)}}
 return <div className="module-page"><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',marginBottom:20}}><div><span className="eyebrow">MASTER · PRODUK</span><h1>{isCat?'Kategori':'Satuan'}</h1><p>{isCat?'Kelompokkan produk untuk kasir, pencarian dan laporan.':'Tentukan satuan dasar dan angka desimal untuk produk.'}</p></div><Button onClick={()=>start()}>+ Tambah {isCat?'Kategori':'Satuan'}</Button></div><div className="module-card" style={{marginBottom:16,padding:16}}><strong>Alur</strong><span style={{display:'block',color:'#64748b',fontSize:12,marginTop:5}}>{isCat?'Buat kategori → pilih pada Produk → gunakan di Penjualan & Laporan':'Buat satuan → pilih sebagai satuan dasar/alternatif → isi konversi di Produk'}</span></div>{error&&<div className="module-alert">{error}</div>}<section className="module-card"><div style={{padding:16,borderBottom:'1px solid #e2e8f0'}}><strong>{isCat?'Daftar Kategori':'Daftar Satuan'}</strong><span style={{display:'block',fontSize:12,color:'#64748b'}}>{loading?'Memuat…':`${rows.length} data`}</span></div>{loading?<div style={{padding:40,textAlign:'center'}}>Memuat…</div>:<div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>Nama</th><th>Kode</th>{!isCat&&<><th>Simbol</th><th>Desimal</th></>}<th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.code}</td>{!isCat&&<><td>{r.symbol||'-'}</td><td>{r.decimal_places}</td></>}<td>{isCat?(r.is_active?'Aktif':'Nonaktif'):'Aktif'}</td><td><button className="table-edit" onClick={()=>start(r)}>Edit</button></td></tr>)}</tbody></table></div>}</section><Modal open={open} title={`${edit?'Edit':'Tambah'} ${isCat?'Kategori':'Satuan'}`} onClose={()=>setOpen(false)}><div className="module-form"><label className="ui-field"><span>Nama *</span><input value={name} onChange={e=>{setName(e.target.value);if(!code||!edit)setCode(makeCode(e.target.value))}} placeholder={isCat?'Contoh: Minuman':'Contoh: Dus'}/></label><label className="ui-field"><span>Kode *</span><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder={isCat?'MINUMAN':'DUS'}/><small>Kode dibuat otomatis dari nama, tetapi tetap bisa diedit.</small></label>{!isCat&&<><label className="ui-field"><span>Simbol</span><input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="Contoh: pcs, kg, dus"/></label><label className="ui-field"><span>Jumlah desimal</span><input type="number" min="0" max="6" value={dec} onChange={e=>setDec(e.target.value)}/><small>Gunakan 0 untuk barang utuh, misalnya pcs/dus.</small></label></>}<div style={{display:'flex',justifyContent:'flex-end',gap:8}}><Button variant="secondary" onClick={()=>setOpen(false)} disabled={saving}>Batal</Button><Button onClick={save} disabled={saving}>{saving?'Menyimpan…':'Simpan'}</Button></div></div></Modal></div>}
