import type { EntityConfig } from './EntityPage'

export const entityConfigs: Record<string, EntityConfig> = {
  products: { title: 'Produk', eyebrow: 'MASTER · PRODUK', description: 'Katalog, SKU, barcode, harga, kategori dan gambar produk.', table: 'products', columns: ['name', 'sku', 'barcode', 'is_active'], businessScoped: true, fields: [{ key: 'name', label: 'Nama produk', required: true }, { key: 'sku', label: 'SKU' }, { key: 'barcode', label: 'Barcode' }] },
  customers: { title: 'Pelanggan', eyebrow: 'MASTER · PELANGGAN', description: 'Data pelanggan, kontak, limit kredit dan saldo piutang.', table: 'customers', columns: ['name', 'phone', 'email', 'credit_limit', 'is_active'], businessScoped: true, fields: [{ key: 'name', label: 'Nama pelanggan', required: true }, { key: 'phone', label: 'Telepon' }, { key: 'email', label: 'Email' }, { key: 'credit_limit', label: 'Limit kredit', type: 'number' }] },
  suppliers: { title: 'Supplier', eyebrow: 'MASTER · SUPPLIER', description: 'Data pemasok dan riwayat hubungan pembelian.', table: 'suppliers', columns: ['name', 'phone', 'email', 'is_active'], businessScoped: true, fields: [{ key: 'name', label: 'Nama supplier', required: true }, { key: 'phone', label: 'Telepon' }, { key: 'email', label: 'Email' }] },
  categories: { title: 'Kategori', eyebrow: 'MASTER · PRODUK', description: 'Pengelompokan katalog untuk kasir dan laporan.', table: 'categories', columns: ['name', 'is_active'], businessScoped: true, fields: [{ key: 'name', label: 'Nama kategori', required: true }] },
  units: { title: 'Satuan', eyebrow: 'MASTER · PRODUK', description: 'Satuan dasar dan satuan penjualan produk.', table: 'units', columns: ['name', 'code'], businessScoped: true, fields: [{ key: 'name', label: 'Nama satuan', required: true }, { key: 'code', label: 'Kode' }] },
  stock: { title: 'Stok', eyebrow: 'MASTER · PERSEDIAAN', description: 'Stok saat ini, stok minimum, penyesuaian dan mutasi menjadi fondasi modul persediaan.', table: 'stock_balances', columns: ['product_id', 'location_id', 'qty_base'], readOnly: true },
  orders: { title: 'Pesanan', eyebrow: 'TRANSAKSI · PESANAN', description: 'Pusat pesanan berjalan, held order dan status fulfillment.', table: 'sales', columns: ['sale_no', 'customer_id', 'total', 'status', 'created_at'], readOnly: true },
  purchases: { title: 'Pembelian', eyebrow: 'TRANSAKSI · PEMBELIAN', description: 'Daftar pembelian dan fondasi penerimaan barang dari supplier.', table: 'purchases', columns: ['purchase_no', 'supplier_id', 'total', 'status', 'created_at'], readOnly: true },
  receivables: { title: 'Piutang', eyebrow: 'KEUANGAN · PIUTANG', description: 'Tagihan pelanggan, jatuh tempo, pembayaran dan riwayat pelunasan.', table: 'receivables', columns: ['customer_id', 'amount', 'due_date', 'status'], readOnly: true },
  payments: { title: 'Pembayaran', eyebrow: 'KEUANGAN · PEMBAYARAN', description: 'Metode pembayaran, transaksi pembayaran dan fondasi rekonsiliasi.', table: 'payments', columns: ['payment_no', 'amount', 'provider', 'status', 'created_at'], readOnly: true },
}
