package com.henky.posqris

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

private val V2Ink=Color(0xFF171B2B); private val V2Muted=Color(0xFF748096); private val V2Brand=Color(0xFF5D3DC6)
private val V2Soft=Color(0xFFF0EAFF); private val V2Bg=Color(0xFFF7F8FC); private val V2Green=Color(0xFF159A6C)
private val V2Amber=Color(0xFFE79A18); private val V2AmberSoft=Color(0xFFFFF4DC)
private data class V2Product(val sku:String,val name:String,val category:String,val price:Long,val stock:Int)
private data class V2Sale(val no:String,val customer:String,val total:Long,val method:String,val time:String)
private data class V2Cart(val product:V2Product,val qty:Int)
private val v2Products=listOf(
 V2Product("SKU-001","Kopi Susu Gula Aren","Minuman",18000,42),V2Product("SKU-002","Americano","Minuman",15000,31),
 V2Product("SKU-003","Matcha Latte","Minuman",22000,18),V2Product("SKU-004","Roti Cokelat","Makanan",12000,27),
 V2Product("SKU-005","Croissant Butter","Makanan",16000,9),V2Product("SKU-006","Nasi Ayam Sambal","Makanan",28000,14),
 V2Product("SKU-007","Air Mineral","Minuman",6000,63),V2Product("SKU-008","Kentang Goreng","Makanan",19000,7),
 V2Product("SKU-009","Teh Lemon","Minuman",14000,22),V2Product("SKU-010","Donat Gula","Makanan",9000,5))
private val v2Sales=listOf(
 V2Sale("TRX-260901-024","Pelanggan Umum",68000,"QRIS","11:08"),V2Sale("TRX-260901-023","Budi",45000,"Tunai","10:52"),
 V2Sale("TRX-260901-022","Pelanggan Umum",32000,"QRIS","10:41"),V2Sale("TRX-260901-021","Sari",92000,"QRIS","10:25"),V2Sale("TRX-260901-020","Pelanggan Umum",28000,"Tunai","10:12"))
private fun v2Money(v:Long)="Rp "+v.toString().reversed().chunked(3).joinToString(".").reversed()
private fun v2Date()=LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy",Locale("id","ID")))

@Composable fun ModernPosAppV2(){
 var page by remember{mutableStateOf("Dashboard")}; var cart by remember{mutableStateOf(emptyList<V2Cart>())}
 val tablet=androidx.compose.ui.platform.LocalConfiguration.current.screenWidthDp>=600
 val pages=listOf("Dashboard","Penjualan","Produk","Persediaan","Pembayaran","Laporan","Pengaturan")
 MaterialTheme(colorScheme=lightColorScheme(primary=V2Brand,background=V2Bg,surface=Color.White,onSurface=V2Ink)){
  Surface(Modifier.fillMaxSize(),color=V2Bg){if(tablet)Row(Modifier.fillMaxSize()){V2Sidebar(page,pages){page=it};Box(Modifier.weight(1f)){V2Content(page,cart,{cart=it})}}else Column(Modifier.fillMaxSize()){Box(Modifier.weight(1f)){V2Content(page,cart,{cart=it})};V2Bottom(page){page=it}}}
 }
}

@Composable private fun V2Sidebar(selected:String,pages:List<String>,onSelect:(String)->Unit){Surface(Modifier.width(244.dp).fillMaxHeight(),color=Color(0xFF171B27)){Column(Modifier.fillMaxSize().padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Row(Modifier.padding(8.dp,8.dp,8.dp,18.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(42.dp).clip(RoundedCornerShape(13.dp)).background(V2Brand),contentAlignment=Alignment.Center){Text("QR",color=Color.White,fontWeight=FontWeight.ExtraBold)};Column(Modifier.padding(start=10.dp)){Text("POS QRIS",color=Color.White,fontSize=18.sp,fontWeight=FontWeight.ExtraBold);Text("Toko Demo • Owner",color=Color(0xFF9CA7BB),fontSize=11.sp)}};pages.forEach{p->val active=p==selected;Surface(Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp)).clickable{onSelect(p)},shape=RoundedCornerShape(12.dp),color=if(active)V2Brand else Color.Transparent){Row(Modifier.padding(12.dp,11.dp),verticalAlignment=Alignment.CenterVertically){Text(v2Glyph(p),color=if(active)Color.White else Color(0xFFAAB4C7),fontSize=18.sp,modifier=Modifier.width(30.dp));Text(p,color=if(active)Color.White else Color(0xFFE6EAF2),fontSize=13.sp,fontWeight=if(active)FontWeight.Bold else FontWeight.Medium)}}};Spacer(Modifier.weight(1f));Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),color=Color(0xFF222838)){Column(Modifier.padding(13.dp)){Text("STATUS TOKO",color=Color(0xFF929DB1),fontSize=10.sp,fontWeight=FontWeight.Bold);Text("●  Online     Supabase",color=Color.White,fontSize=11.sp,fontWeight=FontWeight.SemiBold,modifier=Modifier.padding(top=7.dp))}}}}}
private fun v2Glyph(p:String)=when(p){"Dashboard"->"⌂";"Penjualan"->"＋";"Produk"->"□";"Persediaan"->"▤";"Pembayaran"->"QR";"Laporan"->"▥";else->"⚙"}
@Composable private fun V2Bottom(selected:String,onSelect:(String)->Unit){val items=listOf("Dashboard","Penjualan","Produk","Persediaan");Surface(Modifier.fillMaxWidth().navigationBarsPadding(),color=Color.White,shadowElevation=12.dp){Row(Modifier.padding(6.dp),horizontalArrangement=Arrangement.spacedBy(4.dp)){items.forEach{p->val a=p==selected;Surface(Modifier.weight(1f).clip(RoundedCornerShape(12.dp)).clickable{onSelect(p)},shape=RoundedCornerShape(12.dp),color=if(a)V2Soft else Color.Transparent){Column(Modifier.padding(vertical=7.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(v2Glyph(p),color=if(a)V2Brand else V2Muted,fontSize=17.sp);Text(p,color=if(a)V2Brand else V2Muted,fontSize=10.sp,fontWeight=if(a)FontWeight.Bold else FontWeight.Medium)}}}}}}

@Composable private fun V2Content(page:String,cart:List<V2Cart>,setCart:(List<V2Cart>)->Unit){when(page){"Dashboard"->V2Dashboard{pageNav->setCart(cart);/* navigation is handled by shell */};"Penjualan"->V2Sales(cart,setCart);"Produk"->V2Products();"Persediaan"->V2Inventory();"Pembayaran"->V2Payments();"Laporan"->V2Reports();else->V2Settings()}}
@Composable private fun V2Shell(title:String,subtitle:String,body:@Composable()->Unit){Column(Modifier.fillMaxSize().padding(20.dp,18.dp,20.dp,16.dp)){Text(title,color=V2Ink,fontSize=28.sp,fontWeight=FontWeight.ExtraBold);Text(subtitle,color=V2Muted,fontSize=12.sp,modifier=Modifier.padding(top=3.dp,bottom=16.dp));Box(Modifier.weight(1f).fillMaxWidth()){body()}}}

@Composable private fun V2Dashboard(open:(String)->Unit){V2Shell("Dashboard","Toko Demo • Owner • ${v2Date()}"){LazyColumn(verticalArrangement=Arrangement.spacedBy(14.dp)){item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp),verticalAlignment=Alignment.CenterVertically){Card(Modifier.weight(1f),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(V2Brand)){Column(Modifier.padding(18.dp)){Text("Penjualan hari ini",color=Color(0xFFE9E2FF),fontSize=12.sp);Text(v2Money(1250000),color=Color.White,fontSize=30.sp,fontWeight=FontWeight.ExtraBold);Text("+12,5% dibanding kemarin",color=Color(0xFFD8CCFF),fontSize=10.sp)}};Button({open("Penjualan")},modifier=Modifier.height(74.dp),shape=RoundedCornerShape(14.dp)){Text("＋ Transaksi Baru",fontWeight=FontWeight.Bold)}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){V2Metric("Transaksi","24","hari ini","▣",Modifier.weight(1f));V2Metric("Pembayaran QRIS","Rp 875.000","70% omzet","QR",Modifier.weight(1.15f));V2Metric("Stok menipis","3","perlu perhatian","!",Modifier.weight(1f),true)}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(14.dp)){Card(Modifier.weight(1.3f),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(Color.White)){Column(Modifier.padding(17.dp)){V2Title("Transaksi terbaru","5 transaksi terakhir");v2Sales.forEach{V2SaleRow(it)}}};Card(Modifier.weight(1f),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(Color.White)){Column(Modifier.padding(17.dp)){V2Title("Kinerja hari ini","Status operasional");V2Progress("Target omzet",.72f);V2Progress("QRIS",.70f);V2Progress("Stok aman",.86f);Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp),color=Color(0xFFE8F7F1)){Text("●  Semua sistem berjalan normal",color=V2Green,fontSize=10.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(11.dp))}}}}}}}
@Composable private fun V2Metric(t:String,v:String,n:String,i:String,m:Modifier,w:Boolean=false){Card(m,shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(Color.White),elevation=CardDefaults.cardElevation(1.dp)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(37.dp).clip(RoundedCornerShape(10.dp)).background(if(w)V2AmberSoft else V2Soft),contentAlignment=Alignment.Center){Text(i,color=if(w)V2Amber else V2Brand,fontWeight=FontWeight.Bold,fontSize=12.sp)};Column(Modifier.padding(start=9.dp)){Text(t,color=V2Muted,fontSize=9.sp);Text(v,color=V2Ink,fontSize=16.sp,fontWeight=FontWeight.ExtraBold);Text(n,color=if(w)V2Amber else V2Muted,fontSize=8.sp)}}}}
@Composable private fun V2Title(t:String,s:String){Column{Text(t,color=V2Ink,fontSize=15.sp,fontWeight=FontWeight.ExtraBold);Text(s,color=V2Muted,fontSize=9.sp,modifier=Modifier.padding(top=2.dp))}}
@Composable private fun V2SaleRow(s:V2Sale){Row(Modifier.fillMaxWidth().padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(33.dp).clip(RoundedCornerShape(9.dp)).background(if(s.method=="QRIS")V2Soft else Color(0xFFF1F3F7)),contentAlignment=Alignment.Center){Text(if(s.method=="QRIS")"QR":"Rp",color=if(s.method=="QRIS")V2Brand else V2Muted,fontSize=9.sp,fontWeight=FontWeight.Bold)};Column(Modifier.padding(start=9.dp).weight(1f)){Text(s.no,color=V2Ink,fontSize=10.sp,fontWeight=FontWeight.Bold);Text("${s.customer} • ${s.time}",color=V2Muted,fontSize=8.sp)};Column(horizontalAlignment=Alignment.End){Text(v2Money(s.total),fontSize=10.sp,fontWeight=FontWeight.Bold);Text("LUNAS",color=V2Green,fontSize=8.sp,fontWeight=FontWeight.Bold)}}}
@Composable private fun V2Progress(label:String,value:Float){Column(Modifier.padding(vertical=7.dp)){Row(Modifier.fillMaxWidth()){Text(label,fontSize=9.sp);Spacer(Modifier.weight(1f));Text("${(value*100).toInt()}%",color=V2Brand,fontSize=9.sp,fontWeight=FontWeight.Bold)};Box(Modifier.fillMaxWidth().padding(top=5.dp).height(7.dp).clip(RoundedCornerShape(4.dp)).background(Color(0xFFEEF0F5))){Box(Modifier.fillMaxWidth(value).fillMaxHeight().background(V2Brand))}}}

@Composable private fun V2Sales(cart:List<V2Cart>,setCart:(List<V2Cart>)->Unit){var search by remember{mutableStateOf("")};var cat by remember{mutableStateOf("Semua")};var pay by remember{mutableStateOf(false)};val filtered=v2Products.filter{(cat=="Semua"||it.category==cat)&&(search.isBlank()||it.name.contains(search,true)||it.sku.contains(search,true))};val total=cart.sumOf{it.product.price*it.qty};V2Shell("Penjualan","Kasir • Toko Demo • ${v2Date()}"){Row(Modifier.fillMaxSize(),horizontalArrangement=Arrangement.spacedBy(14.dp)){Column(Modifier.weight(1.5f)){OutlinedTextField(search,{search=it},Modifier.fillMaxWidth(),singleLine=true,shape=RoundedCornerShape(13.dp),label={Text("Cari produk atau SKU")});Row(Modifier.horizontalScroll(rememberScrollState()).padding(vertical=9.dp),horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("Semua","Makanan","Minuman").forEach{Filter2(it,it==cat){cat=it}}};LazyVerticalGrid(columns=GridCells.Adaptive(145.dp),verticalArrangement=Arrangement.spacedBy(9.dp),horizontalArrangement=Arrangement.spacedBy(9.dp)){items(filtered){p->V2ProductTile(p){v2Add(p,cart,setCart)}}}};Card(Modifier.width(325.dp).fillMaxHeight(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(Color.White),elevation=CardDefaults.cardElevation(2.dp)){Column(Modifier.fillMaxSize().padding(16.dp)){Text("Keranjang",fontSize=18.sp,fontWeight=FontWeight.ExtraBold);Text("${cart.sumOf{it.qty}} item",color=V2Muted,fontSize=9.sp);Spacer(Modifier.height(8.dp));if(cart.isEmpty())Box(Modifier.weight(1f).fillMaxWidth(),contentAlignment=Alignment.Center){Text("Belum ada produk",color=V2Muted,fontSize=11.sp)}else LazyColumn(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(8.dp)){items(cart){V2CartRow(it,cart,setCart)}};V2Line("Subtotal",v2Money(total));V2Line("Diskon","Rp 0");Row(Modifier.padding(top=7.dp)){Text("TOTAL",fontWeight=FontWeight.ExtraBold);Spacer(Modifier.weight(1f));Text(v2Money(total),color=V2Brand,fontSize=20.sp,fontWeight=FontWeight.ExtraBold)};Button({if(total>0)pay=true},modifier=Modifier.fillMaxWidth().padding(top=11.dp).height(50.dp),enabled=total>0,shape=RoundedCornerShape(13.dp)){Text("Lanjut Pembayaran",fontWeight=FontWeight.Bold)}}}};if(pay)V2Payment(total){pay=false;setCart(emptyList())}}
@Composable private fun Filter2(t:String,a:Boolean,on:()->Unit){Surface(Modifier.clip(RoundedCornerShape(10.dp)).clickable{on()},shape=RoundedCornerShape(10.dp),color=if(a)V2Brand else Color.White,shadowElevation=if(a)0.dp else 1.dp){Text(t,color=if(a)Color.White else V2Ink,fontSize=10.sp,fontWeight=if(a)FontWeight.Bold else FontWeight.Medium,modifier=Modifier.padding(12.dp,8.dp))}}
@Composable private fun V2ProductTile(p:V2Product,on:()->Unit){Card(Modifier.fillMaxWidth().height(145.dp).clickable{on()},shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(Color.White)){Column(Modifier.padding(12.dp)){Box(Modifier.fillMaxWidth().height(50.dp).clip(RoundedCornerShape(11.dp)).background(V2Soft),contentAlignment=Alignment.Center){Text(p.category.take(1),color=V2Brand,fontSize=20.sp,fontWeight=FontWeight.ExtraBold)};Text(p.name,color=V2Ink,fontSize=10.sp,fontWeight=FontWeight.Bold,maxLines=1,modifier=Modifier.padding(top=8.dp));Row(Modifier.padding(top=4.dp)){Text(v2Money(p.price),color=V2Brand,fontSize=10.sp,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.weight(1f));Text("Stok ${p.stock}",color=if(p.stock<=7)V2Amber else V2Muted,fontSize=8.sp)}}}}
private fun v2Add(p:V2Product,c:List<V2Cart,set:(List<V2Cart>)->Unit){val old=c.firstOrNull{it.product.sku==p.sku};set(if(old==null)c+V2Cart(p,1)else c.map{if(it.product.sku==p.sku)it.copy(qty=it.qty+1)else it})}
@Composable private fun V2CartRow(line:V2Cart,c:List<V2Cart>,set:(List<V2Cart>)->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(line.product.name,fontSize=9.sp,fontWeight=FontWeight.SemiBold);Text(v2Money(line.product.price),color=V2Muted,fontSize=8.sp)};Text("−",Modifier.clickable{v2Qty(line,-1,c,set)},color=V2Brand,fontSize=15.sp,fontWeight=FontWeight.Bold);Text(" ${line.qty} ",fontSize=10.sp,fontWeight=FontWeight.Bold);Text("+",Modifier.clickable{v2Qty(line,1,c,set)},color=V2Brand,fontSize=15.sp,fontWeight=FontWeight.Bold)}}
private fun v2Qty(line:V2Cart,d:Int,c:List<V2Cart>,set:(List<V2Cart>)->Unit){val n=line.qty+d;set(if(n<=0)c.filterNot{it.product.sku==line.product.sku}else c.map{if(it.product.sku==line.product.sku)it.copy(qty=n)else it})}
@Composable private fun V2Line(a:String,b:String){Row(Modifier.fillMaxWidth().padding(vertical=2.dp)){Text(a,color=V2Muted,fontSize=9.sp);Spacer(Modifier.weight(1f));Text(b,color=V2Ink,fontSize=9.sp,fontWeight=FontWeight.SemiBold)}}
@Composable private fun V2Payment(total:Long,done:()->Unit){var method by remember{mutableStateOf("QRIS")};AlertDialog(onDismissRequest=done,title={Text("Pembayaran",fontWeight=FontWeight.ExtraBold)},text={Column(horizontalAlignment=Alignment.CenterHorizontally){Text("Total",color=V2Muted,fontSize=10.sp);Text(v2Money(total),color=V2Brand,fontSize=26.sp,fontWeight=FontWeight.ExtraBold);Row(horizontalArrangement=Arrangement.spacedBy(7.dp),modifier=Modifier.padding(vertical=10.dp)){Filter2("QRIS",method=="QRIS"){method="QRIS"};Filter2("Tunai",method=="Tunai"){method="Tunai"}};if(method=="QRIS")V2Qr()else Text("Pembayaran tunai siap diproses.",color=V2Muted,fontSize=10.sp)}},confirmButton={Button(done,shape=RoundedCornerShape(10.dp)){Text("Simulasikan Dibayar")}},dismissButton={TextButton(done){Text("Batal")}})}
@Composable private fun V2Qr(){Column(horizontalAlignment=Alignment.CenterHorizontally){Box(Modifier.size(150.dp).background(Color.White),contentAlignment=Alignment.Center){Column(verticalArrangement=Arrangement.spacedBy(2.dp)){repeat(10){r->Row(horizontalArrangement=Arrangement.spacedBy(2.dp)){repeat(10){c->Box(Modifier.size(11.dp).background(if((r*5+c*7+r)%3==0)Color.White else Color.Black))}}}}};Text("QRIS • Toko Demo",fontSize=10.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=6.dp));Text("Demo UI • QR asli dari konfigurasi toko",color=V2Muted,fontSize=8.sp)}}

@Composable private fun V2Products(){V2Shell("Produk","Katalog, harga, kategori, dan status produk"){LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(v2Products){p->Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(Color.White)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(36.dp).clip(RoundedCornerShape(10.dp)).background(V2Soft),contentAlignment=Alignment.Center){Text(p.category.take(1),color=V2Brand,fontWeight=FontWeight.Bold)};Column(Modifier.padding(start=9.dp).weight(1f)){Text(p.name,fontSize=11.sp,fontWeight=FontWeight.Bold);Text("${p.sku} • ${p.category}",color=V2Muted,fontSize=8.sp)};Column(horizontalAlignment=Alignment.End){Text(v2Money(p.price),color=V2Brand,fontSize=10.sp,fontWeight=FontWeight.Bold);Text("Stok ${p.stock}",color=if(p.stock<=7)V2Amber else V2Green,fontSize=8.sp)}}}}}}}
@Composable private fun V2Inventory(){V2Shell("Persediaan","Pantau stok minimum dan kebutuhan restock"){LazyColumn(verticalArrangement=Arrangement.spacedBy(9.dp)){item{Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){V2Metric("Total SKU","10","aktif","□",Modifier.weight(1f));V2Metric("Stok aman","7","SKU","✓",Modifier.weight(1f));V2Metric("Restock","3","SKU","!",Modifier.weight(1f),true)}};item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(Color.White)){Column(Modifier.padding(15.dp)){V2Title("Monitoring stok","Paling kritis di atas");v2Products.sortedBy{it.stock}.forEach{p->V2Line(p.name,"${p.stock} unit")}}}}}}}
@Composable private fun V2Payments(){V2Shell("Pembayaran","Pantau pembayaran QRIS dan transaksi kasir"){LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){item{Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){V2Metric("QRIS","Rp 875.000","21 transaksi","QR",Modifier.weight(1f));V2Metric("Berhasil","24","100%","✓",Modifier.weight(1f));V2Metric("Menunggu","0","transaksi","…",Modifier.weight(1f))}};item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(Color.White)){Column(Modifier.padding(15.dp)){V2Title("Riwayat pembayaran","Terbaru");v2Sales.forEach{V2SaleRow(it)}}}};item{Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),color=V2Soft){Column(Modifier.padding(15.dp)){Text("QRIS toko",color=V2Brand,fontSize=14.sp,fontWeight=FontWeight.ExtraBold);Text("Toko Demo • merchant aktif",fontSize=10.sp);OutlinedButton({},modifier=Modifier.padding(top=7.dp),shape=RoundedCornerShape(10.dp)){Text("Kelola QRIS")}}}}}}}
@Composable private fun V2Reports(){V2Shell("Laporan","Ringkasan performa penjualan dan pembayaran"){LazyColumn(verticalArrangement=Arrangement.spacedBy(11.dp)){item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(Color.White)){Column(Modifier.padding(16.dp)){V2Title("Penjualan 7 hari","Data demo untuk validasi UI");listOf(.45f,.63f,.51f,.78f,.68f,.91f,.72f).forEachIndexed{i,v->V2Progress("Hari ${i+1}",v)}}}};item{Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){V2Metric("Omzet","Rp 8,42 jt","bulan ini","Rp",Modifier.weight(1f));V2Metric("Rata-rata","Rp 52.900","per transaksi","↗",Modifier.weight(1f));V2Metric("Terlaris","Kopi Susu","42 terjual","★",Modifier.weight(1f))}}}}}
@Composable private fun V2Settings(){V2Shell("Pengaturan","Konfigurasi toko, QRIS, struk, printer, dan hak akses"){LazyColumn(verticalArrangement=Arrangement.spacedBy(9.dp)){item{V2Setting("Toko & Cabang","Toko Demo","Toko Utama • aktif")};item{V2Setting("QRIS","QRIS Statis","Merchant aktif • siap digunakan kasir")};item{V2Setting("Struk","58 mm","Logo, alamat, footer, format kertas")};item{V2Setting("Printer","Belum dipasangkan","Bluetooth / LAN / USB")};item{V2Setting("Role & Akses","Owner","Hak akses penuh • demo mode")};item{V2Setting("Koneksi","Supabase","Connected • publishable key")}}}}
@Composable private fun V2Setting(t:String,v:String,d:String){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(Color.White)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(t,fontSize=11.sp,fontWeight=FontWeight.ExtraBold);Text(v,color=V2Brand,fontSize=11.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=3.dp));Text(d,color=V2Muted,fontSize=8.sp)}};Text("›",color=V2Muted,fontSize=20.sp)}}
