'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { getActiveWorkspace } from '../../lib/business-context'
import { requireSupabase } from '../../lib/supabase'
import styles from './InventoryWorkspace.module.css'

type Product = { id:string; name:string; sku:string; base_unit_id:string; current_cost:number; reorder_point:number; min_stock:number }
type Stock = { product_id:string; location_id:string; qty_base:number; reserved_qty:number }
type Movement = { id:string; product_id:string; movement_type:string; qty_base:number; unit_cost:number; reference_type:string|null; reference_id:string|null; reason:string|null; created_at:string }

const money=(v:number)=>`Rp ${Math.round(Number(v||0)).toLocaleString('id-ID')}`
const qty=(v:number)=>Number(v||0).toLocaleString('id-ID',{maximumFractionDigits:3})
const date=(v:string)=>new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))

export default function InventoryPage(){
 const [products,setProducts]=useState<Product[]>([]); const [stock,setStock]=useState<Stock[]>([]); const [movements,setMovements]=useState<Movement[]>([])
 const [productId,setProductId]=useState(''); const [direction,setDirection]=useState<'IN'|'OUT'>('IN'); const [amount,setAmount]=useState(''); const [reason,setReason]=useState(''); const [search,setSearch]=useState('')
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const db=requireSupabase();const {business,branch}=await getActiveWorkspace();const [{data:p,error:pe},{data:s,error:se},{data:m,error:me}]=await Promise.all([
   db.from('products').select('id,name,sku,base_unit_id,current_cost,reorder_point,min_stock').eq('business_id',business.id).eq('is_active',true).order('name').limit(2000),
   db.from('stock_balances').select('product_id,location_id,qty_base,reserved_qty').eq('location_id',(await db.from('locations').select('id').eq('branch_id',branch.id).eq('is_active',true).limit(1)).data?.[0]?.id||'').limit(3000),
   db.from('stock_movements').select('id,product_id,movement_type,qty_base,unit_cost,reference_type,reference_id,reason,created_at').eq('branch_id',branch.id).order('created_at',{ascending:false}).limit(100)
 ]);if(pe)throw pe;if(se)throw se;if(me)throw me;setProducts(p||[]);setStock(s||[]);setMovements(m||[])}catch(e:any){setError(e?.message||'Gagal memuat persediaan.')}finally{setLoading(false)}},[])
 useEffect(()=>{load()},[load])
 const map=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]); const visible=useMemo(()=>products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(search.toLowerCase())),[products,search])
 const totalQty=stock.reduce((a,x)=>a+Number(x.qty_base||0),0); const reserved=stock.reduce((a,x)=>a+Number(x.reserved_qty||0),0); const inventoryValue=stock.reduce((a,x)=>a+Math.max(0,Number(x.qty_base||0)-Number(x.reserved_qty||0))*Number(map.get(x.product_id)?.current_cost||0),0); const critical=stock.filter(x=>{const p=map.get(x.product_id);return p&&Number(x.qty_base||0)-Number(x.reserved_qty||0)<=Math.max(Number(p.reorder_point||0),Number(p.min_stock||0))}).length; const negative=stock.filter(x=>Number(x.qty_base||0)<0).length
 async function adjust(){setError('');setMessage('');const n=Number(amount);if(!productId)return setError('Produk wajib dipilih.');if(!Number.isFinite(n)||n<=0)return setError('Jumlah adjustment harus lebih dari 0.');if(!reason.trim())return setError('Alasan adjustment wajib diisi.');setSaving(true);try{const db=requireSupabase();const {data,error:e}=await db.rpc('ubah_stok_atomic',{p_location_id:stock.find(x=>x.product_id===productId)?.location_id,p_product_id:productId,p_quantity:direction==='IN'?n:-n,p_reference_type:direction==='IN'?'ADJUSTMENT_IN':'ADJUSTMENT_OUT',p_note:reason.trim()});if(e)throw e;setAmount('');setReason('');setMessage(`Adjustment berhasil. Saldo baru ${qty(Number(data))}.`);await load()}catch(e:any){setError(e?.message||'Adjustment gagal.')}finally{setSaving(false)}}
 return <div className={styles.page}><div className={styles.hero}><div><span>INVENTORY CONTROL</span><h1>Persediaan</h1><p>Saldo stok bukan CRUD. Perubahan harus meninggalkan jejak movement agar audit tidak berubah menjadi seni abstrak.</p></div><div className={styles.stats}><div><small>Qty fisik</small><strong>{qty(totalQty)}</strong></div><div><small>Reserved</small><strong>{qty(reserved)}</strong></div><div><small>Nilai tersedia</small><strong>{money(inventoryValue)}</strong></div><div><small>Stok kritis</small><strong>{critical}</strong></div></div></div>
 {error&&<div className={styles.alert}>{error}</div>}{message&&<div className={styles.success}>{message}</div>}{negative>0&&<div className={styles.warning}><strong>{negative} saldo stok negatif terdeteksi.</strong><span>Data historis tidak diubah otomatis. Periksa movement dan lakukan adjustment resmi bila memang diperlukan.</span></div>}
 <div className={styles.grid}><section className={styles.card}><div className={styles.head}><div><strong>Posisi stok</strong><span>Per lokasi aktif · unit dasar</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari SKU / produk..."/></div>{loading?<div className={styles.empty}>Memuat saldo stok...</div>:<div className={styles.table}><div className={styles.row}><b>SKU</b><b>Produk</b><b>Stok</b><b>Reserved</b><b>Available</b><b>HPP</b></div>{visible.map(p=>{const s=stock.find(x=>x.product_id===p.id);const qn=Number(s?.qty_base||0),rv=Number(s?.reserved_qty||0);return <div className={styles.row} key={p.id}><span>{p.sku}</span><span>{p.name}</span><span>{qty(qn)}</span><span>{qty(rv)}</span><span>{qty(qn-rv)}</span><span>{money(p.current_cost)}</span></div>})}{visible.length===0&&<div className={styles.empty}>Tidak ada produk yang cocok.</div>}</div>}</section>
 <aside className={styles.card}><div className={styles.head}><div><strong>Adjustment stok</strong><span>Untuk koreksi fisik atau hasil stock opname</span></div></div><label>Produk<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Pilih produk</option>{visible.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><div className={styles.segment}><button className={direction==='IN'?styles.active:''} onClick={()=>setDirection('IN')}>+ Masuk</button><button className={direction==='OUT'?styles.active:''} onClick={()=>setDirection('OUT')}>− Keluar</button></div><label>Jumlah<input type="number" min="0.001" step="0.001" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label><label>Alasan<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Contoh: hasil stock opname 4 Sep 2026"/></label><button className={styles.primary} disabled={saving} onClick={adjust}>{saving?'Memproses...':'Simpan adjustment'}</button><small>Adjustment akan tercatat sebagai stock movement ADJUSTMENT_IN/OUT.</small></aside></div>
 <section className={styles.card}><div className={styles.head}><div><strong>Riwayat movement</strong><span>100 movement terakhir di cabang aktif</span></div><button className={styles.ghost} onClick={load}>Muat ulang</button></div><div className={styles.table}><div className={styles.row}><b>Waktu</b><b>Produk</b><b>Jenis</b><b>Qty</b><b>Unit cost</b><b>Referensi / alasan</b></div>{movements.map(m=><div className={styles.row} key={m.id}><span>{date(m.created_at)}</span><span>{map.get(m.product_id)?.sku||'-'} · {map.get(m.product_id)?.name||'Produk'}</span><span>{m.movement_type}</span><span>{qty(m.qty_base)}</span><span>{money(m.unit_cost)}</span><span>{m.reason||m.reference_type||'-'}</span></div>)}{movements.length===0&&<div className={styles.empty}>Belum ada movement stok.</div>}</div></section></div>
}
